/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasPanel;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author melis
 */
public class PlanOpPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form PlanOpPanel1
     */
    public PlanOpPanel1() {
        initComponents();
        jlbNewCantGigas.setVisible(false);
        jlbNewCantMinutos.setVisible(false);
        jlbNewNombrePlan.setVisible(false);
        jlbNewNumTelefono.setVisible(false);
        jlbNewPrecio.setVisible(false);
        jlbNuevoPlanAdquirido.setVisible(false);
        jlbPrefijoNumero.setVisible(false);
        
    }

    public JButton getBtnSelecPlanInicial() {
        return btnSelecPlanInicial;
    }

    public JButton getBtnSelecPlanPerso() {
        return btnSelecPlanPerso;
    }

    public JButton getBtnSelecPlanPro() {
        return btnSelecPlanPro;
    }

    public JButton getBtnSelecPlanUltra() {
        return btnSelecPlanUltra;
    }

    public String getTxtGigasPlanPerso() {
        return txtGigasPlanPerso.getText();
    }

    public String getTxtMinutosPlanPerso() {
        return txtMinutosPlanPerso.getText();
    }

    public String getTxtNumeroPlanPerso() {
        return txtNumeroPlanPerso.getText();
    }
    
    public void setJlbNewCantGigas(String msg) {
        this.jlbNewCantGigas.setText(msg);
    }

    public void setJlbNewCantMinutos(String msg) {
        this.jlbNewCantMinutos.setText(msg);
    }

    public void setJlbNewNombrePlan(String msg) {
        this.jlbNewNombrePlan.setText(msg);
    }

    public void setJlbNewNumTelefono(String msg) {
        this.jlbNewNumTelefono.setText(msg);
    }

    public void setJlbNewPrecio(String msg) {
        this.jlbNewPrecio.setText(msg);
    }

    
    public JLabel getJlbNewCantGigas() {
        return jlbNewCantGigas;
    }

    public JLabel getJlbNewCantMinutos() {
        return jlbNewCantMinutos;
    }

    public JLabel getJlbNewNombrePlan() {
        return jlbNewNombrePlan;
    }

    public JLabel getJlbNewNumTelefono() {
        return jlbNewNumTelefono;
    }

    public JLabel getJlbNewPrecio() {
        return jlbNewPrecio;
    }

    public JLabel getJlbNuevoPlanAdquirido() {
        return jlbNuevoPlanAdquirido;
    }

    public JLabel getJlbPrefijoNumero() {
        return jlbPrefijoNumero;
    }
    
    public void setJlbNumeroPersoVacio(String msg,Color color){
        this.jlbNumeroPersoVacio.setText(msg);
        this.jlbNumeroPersoVacio.setForeground(color);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbSeleccPlan = new javax.swing.JLabel();
        jlbTituloPlanInicial = new javax.swing.JLabel();
        jlbGigasPlanInicial = new javax.swing.JLabel();
        jlbMinutosPlanInicial = new javax.swing.JLabel();
        jlbPrecioPlanInicial = new javax.swing.JLabel();
        btnSelecPlanInicial = new javax.swing.JButton();
        jlbTituloPlanPro = new javax.swing.JLabel();
        jlbGigasPlanPro = new javax.swing.JLabel();
        jlbMinutosPlanPro = new javax.swing.JLabel();
        jlbPrecioPlanPro = new javax.swing.JLabel();
        btnSelecPlanPro = new javax.swing.JButton();
        jlbTituloPlanUltra = new javax.swing.JLabel();
        jlbGigasPlanUltra = new javax.swing.JLabel();
        jlbMinutosPlanUltra = new javax.swing.JLabel();
        jlbPrecioPlanUltra = new javax.swing.JLabel();
        btnSelecPlanUltra = new javax.swing.JButton();
        jlbNuevoPlanAdquirido = new javax.swing.JLabel();
        jlbNewNombrePlan = new javax.swing.JLabel();
        jlbPrefijoNumero = new javax.swing.JLabel();
        jlbNewNumTelefono = new javax.swing.JLabel();
        jlbNewCantGigas = new javax.swing.JLabel();
        jlbNewCantMinutos = new javax.swing.JLabel();
        jlbNewPrecio = new javax.swing.JLabel();
        jlbTituloPlanPerso = new javax.swing.JLabel();
        txtGigasPlanPerso = new javax.swing.JTextField();
        jlbGigasPlanPerso = new javax.swing.JLabel();
        jlbMinutosPlanPerso = new javax.swing.JLabel();
        jlbNumeroPlanPerso = new javax.swing.JLabel();
        jlbNumeroPersoVacio = new javax.swing.JLabel();
        txtMinutosPlanPerso = new javax.swing.JTextField();
        txtNumeroPlanPerso = new javax.swing.JTextField();
        btnSelecPlanPerso = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(406, 599));

        jlbSeleccPlan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbSeleccPlan.setText("Seleccione un plan:");

        jlbTituloPlanInicial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloPlanInicial.setText("Plan Inicial");

        jlbGigasPlanInicial.setText("100 Gigas");

        jlbMinutosPlanInicial.setText("1000 Minutos");

        jlbPrecioPlanInicial.setText("$8.792");

        btnSelecPlanInicial.setText("Inicial");
        btnSelecPlanInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecPlanInicialActionPerformed(evt);
            }
        });

        jlbTituloPlanPro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloPlanPro.setText("Plan Pro");

        jlbGigasPlanPro.setText("200 Gigas");

        jlbMinutosPlanPro.setText("1000 Minutos");

        jlbPrecioPlanPro.setText("$11.192");

        btnSelecPlanPro.setText("Pro");

        jlbTituloPlanUltra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloPlanUltra.setText("Plan Ultra");

        jlbGigasPlanUltra.setText("300 Gigas");

        jlbMinutosPlanUltra.setText("1000 Minutos");

        jlbPrecioPlanUltra.setText("$13.592");

        btnSelecPlanUltra.setText("Ultra");
        btnSelecPlanUltra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecPlanUltraActionPerformed(evt);
            }
        });

        jlbNuevoPlanAdquirido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbNuevoPlanAdquirido.setText("Nuevo plan adquirido:");

        jlbNewNombrePlan.setText("nombre plan");

        jlbPrefijoNumero.setText("+56 9");

        jlbNewNumTelefono.setText("numero telefono");

        jlbNewCantGigas.setText("cantidad de giga bytes");

        jlbNewCantMinutos.setText("cantidad de minutos libres");

        jlbNewPrecio.setText("precio");

        jlbTituloPlanPerso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloPlanPerso.setText("Plan personalizado");

        jlbGigasPlanPerso.setText("Cantidad de GB :");

        jlbMinutosPlanPerso.setText("Cantidad de minutos:");

        jlbNumeroPlanPerso.setText("Numero de telefono: +56 9");

        jlbNumeroPersoVacio.setForeground(new java.awt.Color(102, 102, 102));
        jlbNumeroPersoVacio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbNumeroPersoVacio.setText("si no introduce un numero le generaremos uno");

        btnSelecPlanPerso.setText("Personalizado");
        btnSelecPlanPerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecPlanPersoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbNumeroPlanPerso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumeroPlanPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbGigasPlanPerso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGigasPlanPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbMinutosPlanPerso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMinutosPlanPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSelecPlanPerso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbNumeroPersoVacio))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbTituloPlanInicial)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSelecPlanInicial)
                                            .addComponent(jlbPrecioPlanInicial)
                                            .addComponent(jlbMinutosPlanInicial)
                                            .addComponent(jlbGigasPlanInicial))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbTituloPlanPro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSelecPlanPro)
                                            .addComponent(jlbPrecioPlanPro)
                                            .addComponent(jlbMinutosPlanPro)
                                            .addComponent(jlbGigasPlanPro))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbTituloPlanUltra)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSelecPlanUltra)
                                            .addComponent(jlbPrecioPlanUltra)
                                            .addComponent(jlbMinutosPlanUltra)
                                            .addComponent(jlbGigasPlanUltra)))))
                            .addComponent(jlbSeleccPlan)
                            .addComponent(jlbTituloPlanPerso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNuevoPlanAdquirido)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbPrefijoNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbNewNumTelefono))
                                    .addComponent(jlbNewNombrePlan)
                                    .addComponent(jlbNewCantGigas)
                                    .addComponent(jlbNewCantMinutos)
                                    .addComponent(jlbNewPrecio))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbTituloPlanUltra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbGigasPlanUltra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbMinutosPlanUltra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbPrecioPlanUltra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelecPlanUltra))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbSeleccPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbTituloPlanInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbGigasPlanInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbMinutosPlanInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPrecioPlanInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelecPlanInicial))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbTituloPlanPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbGigasPlanPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbMinutosPlanPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbPrecioPlanPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelecPlanPro)))))
                .addGap(18, 18, 18)
                .addComponent(jlbTituloPlanPerso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGigasPlanPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGigasPlanPerso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMinutosPlanPerso)
                    .addComponent(txtMinutosPlanPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNumeroPlanPerso)
                    .addComponent(txtNumeroPlanPerso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecPlanPerso)
                    .addComponent(jlbNumeroPersoVacio))
                .addGap(46, 46, 46)
                .addComponent(jlbNuevoPlanAdquirido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNewNombrePlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrefijoNumero)
                    .addComponent(jlbNewNumTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNewCantGigas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNewCantMinutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNewPrecio)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecPlanInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecPlanInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecPlanInicialActionPerformed

    private void btnSelecPlanUltraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecPlanUltraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecPlanUltraActionPerformed

    private void btnSelecPlanPersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecPlanPersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecPlanPersoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecPlanInicial;
    private javax.swing.JButton btnSelecPlanPerso;
    private javax.swing.JButton btnSelecPlanPro;
    private javax.swing.JButton btnSelecPlanUltra;
    private javax.swing.JLabel jlbGigasPlanInicial;
    private javax.swing.JLabel jlbGigasPlanPerso;
    private javax.swing.JLabel jlbGigasPlanPro;
    private javax.swing.JLabel jlbGigasPlanUltra;
    private javax.swing.JLabel jlbMinutosPlanInicial;
    private javax.swing.JLabel jlbMinutosPlanPerso;
    private javax.swing.JLabel jlbMinutosPlanPro;
    private javax.swing.JLabel jlbMinutosPlanUltra;
    private javax.swing.JLabel jlbNewCantGigas;
    private javax.swing.JLabel jlbNewCantMinutos;
    private javax.swing.JLabel jlbNewNombrePlan;
    private javax.swing.JLabel jlbNewNumTelefono;
    private javax.swing.JLabel jlbNewPrecio;
    private javax.swing.JLabel jlbNuevoPlanAdquirido;
    private javax.swing.JLabel jlbNumeroPersoVacio;
    private javax.swing.JLabel jlbNumeroPlanPerso;
    private javax.swing.JLabel jlbPrecioPlanInicial;
    private javax.swing.JLabel jlbPrecioPlanPro;
    private javax.swing.JLabel jlbPrecioPlanUltra;
    private javax.swing.JLabel jlbPrefijoNumero;
    private javax.swing.JLabel jlbSeleccPlan;
    private javax.swing.JLabel jlbTituloPlanInicial;
    private javax.swing.JLabel jlbTituloPlanPerso;
    private javax.swing.JLabel jlbTituloPlanPro;
    private javax.swing.JLabel jlbTituloPlanUltra;
    private javax.swing.JTextField txtGigasPlanPerso;
    private javax.swing.JTextField txtMinutosPlanPerso;
    private javax.swing.JTextField txtNumeroPlanPerso;
    // End of variables declaration//GEN-END:variables
}
