/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasPanel;

/**
 *
 * @author melis
 */
public class PlanOpPanel4 extends javax.swing.JPanel {

    /**
     * Creates new form PlanOpPanel4
     */
    public PlanOpPanel4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTituloOpEliminarPlanes = new javax.swing.JLabel();
        jlbNombreCliente = new javax.swing.JLabel();
        jlbTituloOpEliminarPlanes2 = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();

        jlbTituloOpEliminarPlanes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloOpEliminarPlanes.setText("El cliente");

        jlbNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbNombreCliente.setText("NOMBRE");

        jlbTituloOpEliminarPlanes2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloOpEliminarPlanes2.setText("ha eliminado todos sus planes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbTituloOpEliminarPlanes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbNombreCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbTituloOpEliminarPlanes2)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTituloOpEliminarPlanes)
                    .addComponent(jlbNombreCliente)
                    .addComponent(jlbTituloOpEliminarPlanes2))
                .addGap(37, 37, 37)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbNombreCliente;
    private javax.swing.JLabel jlbTituloOpEliminarPlanes;
    private javax.swing.JLabel jlbTituloOpEliminarPlanes2;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
