/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasPanel;

/**
 *
 * @author melis
 */
public class PlanOpPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form PlanOpPanel1
     */
    public PlanOpPanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbSeleccPlan = new javax.swing.JLabel();
        jlbTituloPlanUno = new javax.swing.JLabel();
        jlbGigasPlanUno = new javax.swing.JLabel();
        jlbMinutosPlanUno = new javax.swing.JLabel();
        jlbPrecioPlanUno = new javax.swing.JLabel();
        btnSelecPlanUno = new javax.swing.JButton();
        jlbTituloPlanDos = new javax.swing.JLabel();
        jlbGigasPlanDos = new javax.swing.JLabel();
        jlbMinutosPlanDos = new javax.swing.JLabel();
        jlbPrecioPlanDos = new javax.swing.JLabel();
        btnSelecPlanDos = new javax.swing.JButton();
        jlbTituloPlanTres = new javax.swing.JLabel();
        jlbGigasPlanTres = new javax.swing.JLabel();
        jlbMinutosPlanTres = new javax.swing.JLabel();
        jlbPrecioPlanTres = new javax.swing.JLabel();
        btnSelecPlanTres = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(406, 599));

        jlbSeleccPlan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbSeleccPlan.setText("Seleccione un plan:");

        jlbTituloPlanUno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloPlanUno.setText("Plan Inicial");

        jlbGigasPlanUno.setText("100 Gigas");

        jlbMinutosPlanUno.setText("1000 Minutos");

        jlbPrecioPlanUno.setText("$8.792");

        btnSelecPlanUno.setText("Inicial");
        btnSelecPlanUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecPlanUnoActionPerformed(evt);
            }
        });

        jlbTituloPlanDos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloPlanDos.setText("Plan Full");

        jlbGigasPlanDos.setText("200 Gigas");

        jlbMinutosPlanDos.setText("1000 Minutos");

        jlbPrecioPlanDos.setText("$11.192");

        btnSelecPlanDos.setText("Full");

        jlbTituloPlanTres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloPlanTres.setText("Plan Pro");

        jlbGigasPlanTres.setText("300 Gigas");

        jlbMinutosPlanTres.setText("1000 Minutos");

        jlbPrecioPlanTres.setText("$13.592");

        btnSelecPlanTres.setText("Pro");
        btnSelecPlanTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecPlanTresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSeleccPlan)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTituloPlanTres)
                            .addComponent(jlbTituloPlanDos)
                            .addComponent(jlbTituloPlanUno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSelecPlanDos)
                                .addComponent(jlbPrecioPlanDos)
                                .addComponent(jlbMinutosPlanDos)
                                .addComponent(jlbGigasPlanDos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSelecPlanUno)
                                .addComponent(jlbPrecioPlanUno)
                                .addComponent(jlbMinutosPlanUno)
                                .addComponent(jlbGigasPlanUno))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSelecPlanTres)
                                .addComponent(jlbPrecioPlanTres)
                                .addComponent(jlbMinutosPlanTres)
                                .addComponent(jlbGigasPlanTres)))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlbSeleccPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbTituloPlanUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbGigasPlanUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMinutosPlanUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbPrecioPlanUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecPlanUno)
                .addGap(18, 18, 18)
                .addComponent(jlbTituloPlanDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbGigasPlanDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMinutosPlanDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbPrecioPlanDos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecPlanDos)
                .addGap(18, 18, 18)
                .addComponent(jlbTituloPlanTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbGigasPlanTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMinutosPlanTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbPrecioPlanTres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecPlanTres)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecPlanUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecPlanUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecPlanUnoActionPerformed

    private void btnSelecPlanTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecPlanTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecPlanTresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecPlanDos;
    private javax.swing.JButton btnSelecPlanTres;
    private javax.swing.JButton btnSelecPlanUno;
    private javax.swing.JLabel jlbGigasPlanDos;
    private javax.swing.JLabel jlbGigasPlanTres;
    private javax.swing.JLabel jlbGigasPlanUno;
    private javax.swing.JLabel jlbMinutosPlanDos;
    private javax.swing.JLabel jlbMinutosPlanTres;
    private javax.swing.JLabel jlbMinutosPlanUno;
    private javax.swing.JLabel jlbPrecioPlanDos;
    private javax.swing.JLabel jlbPrecioPlanTres;
    private javax.swing.JLabel jlbPrecioPlanUno;
    private javax.swing.JLabel jlbSeleccPlan;
    private javax.swing.JLabel jlbTituloPlanDos;
    private javax.swing.JLabel jlbTituloPlanTres;
    private javax.swing.JLabel jlbTituloPlanUno;
    // End of variables declaration//GEN-END:variables
}
