/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasPanel;

/**
 *
 * @author melis
 */
public class PlanOpPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form PlanOpPanel2
     */
    public PlanOpPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTituloMostrar = new javax.swing.JLabel();
        jlbNombreCliente = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();

        setPreferredSize(new java.awt.Dimension(406, 599));

        jlbTituloMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloMostrar.setText("Planes asociados a");

        jlbNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbNombreCliente.setText("NOMBRE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbTituloMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbNombreCliente)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTituloMostrar)
                    .addComponent(jlbNombreCliente))
                .addGap(32, 32, 32)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbNombreCliente;
    private javax.swing.JLabel jlbTituloMostrar;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
