/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasPanel;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melis
 */
public class PlanOpPanel2 extends javax.swing.JPanel {

    public void setJlbNombreCliente(String nombreCliente) {
        this.jlbNombreCliente.setText(nombreCliente);
    }
    

    /**
     * Creates new form PlanOpPanel2
     */
    public PlanOpPanel2() {
        initComponents();
    }
    
    public void listTabPlanes(String[] arregloPlanes){
        DefaultTableModel model = (DefaultTableModel) tblListarPlanes.getModel();
        for(int i = 0 ; i < arregloPlanes.length; i++) {
            String[] arregloPlanesAux = arregloPlanes[i].split(",");
            model.addRow(arregloPlanesAux);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTituloMostrar = new javax.swing.JLabel();
        jlbNombreCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarPlanes = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(406, 599));

        jlbTituloMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloMostrar.setText("Planes asociados a");

        jlbNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbNombreCliente.setText("NOMBRE");

        tblListarPlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Plan", "Número fijo", "Gigabytes", "Minutos", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListarPlanes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbTituloMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbNombreCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTituloMostrar)
                    .addComponent(jlbNombreCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbNombreCliente;
    private javax.swing.JLabel jlbTituloMostrar;
    private javax.swing.JTable tblListarPlanes;
    // End of variables declaration//GEN-END:variables

}
