/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistasPanel;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author melis
 */
public class PlanOpPanel3 extends javax.swing.JPanel {

    
    
    
    public JButton getBtnEliminarPlan() {
        return btnEliminarPlan;
    }

    public void setJlbEstadoPlan(String msg,Color color) {
        this.jlbEstadoPlan.setText(msg);
        this.jlbEstadoPlan.setForeground(color);
    }
    
    public JLabel getJlbEstadoPlan() {
        return jlbEstadoPlan;
    }

    public String getTxtEliminarPlan() {
        return txtEliminarPlan.getText();
    }


    public PlanOpPanel3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEliminarPlan = new javax.swing.JTextField();
        btnEliminarPlan = new javax.swing.JButton();
        jlbEstadoPlan = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese el numero de telefono del plan que desea eliminar:");

        txtEliminarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarPlanActionPerformed(evt);
            }
        });

        btnEliminarPlan.setText("Eliminar");

        jlbEstadoPlan.setText("texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbEstadoPlan)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEliminarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarPlan)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEliminarPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarPlan))
                .addGap(27, 27, 27)
                .addComponent(jlbEstadoPlan)
                .addContainerGap(453, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEliminarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEliminarPlanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbEstadoPlan;
    private javax.swing.JTextField txtEliminarPlan;
    // End of variables declaration//GEN-END:variables
}
