/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author melis
 */
public class MenuPlan extends javax.swing.JFrame {

    /**
     * Creates new form MenuPlan
     */
    public MenuPlan() {
        initComponents();
    }

    public JButton getBtnBuscarRut() {
        return btnBuscarRut;
    }
    public JButton getBtnAgregarPlan() {
        return btnAgregarPlan;
    }
    public JButton getBtnMostrarPlanes() {
        return btnMostrarPlanes;
    }    
    public JButton getBtnEliminarPlan() {
        return btnEliminarPlan;
    }
    public JButton getBtnVolver() {
        return btnVolver;
    }
    public JButton getBtnModificarPlan() {
        return btnModificarPlan;
    }
    public JLabel getJlbExisteRut() {
        return jlbExisteRut;
    }
    public JLabel getJlbTituloOpciones() {
        return jlbTituloOpciones;
    }
    public String getTxtRutBuscado() {
        return txtRutBuscado.getText();
    }

    public void setJlbExisteRut(String msg, Color color) {
        this.jlbExisteRut.setText(msg);
        this.jlbExisteRut.setForeground(color);
    }
    
    public void mostrarPanel(JPanel p){
        p.setSize(470, 600);
        p.setLocation(0,0);
        pnlPanelOpciones.removeAll();
        pnlPanelOpciones.add(p,BorderLayout.CENTER);
        pnlPanelOpciones.revalidate();
        pnlPanelOpciones.repaint();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTituloRutCliente = new javax.swing.JLabel();
        btnBuscarRut = new javax.swing.JButton();
        jlbExisteRut = new javax.swing.JLabel();
        btnAgregarPlan = new javax.swing.JButton();
        jlbTituloOpciones = new javax.swing.JLabel();
        btnMostrarPlanes = new javax.swing.JButton();
        btnEliminarPlan = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        pnlPanelOpciones = new java.awt.Panel();
        txtRutBuscado = new javax.swing.JTextField();
        btnModificarPlan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbTituloRutCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloRutCliente.setText("Ingrese el rut del cliente que desea operar");

        btnBuscarRut.setText("buscar");

        jlbExisteRut.setForeground(new java.awt.Color(102, 102, 102));
        jlbExisteRut.setText("sin puntos, ni guion ni digito verificador");

        btnAgregarPlan.setText("1.- Agregar un plan");
        btnAgregarPlan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlbTituloOpciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTituloOpciones.setText("Elija la opción que desea realizar:");

        btnMostrarPlanes.setText("2.- Mostrar planes");
        btnMostrarPlanes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnEliminarPlan.setText("3.- Eliminar un plan");
        btnEliminarPlan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnVolver.setText("Volver");

        javax.swing.GroupLayout pnlPanelOpcionesLayout = new javax.swing.GroupLayout(pnlPanelOpciones);
        pnlPanelOpciones.setLayout(pnlPanelOpcionesLayout);
        pnlPanelOpcionesLayout.setHorizontalGroup(
            pnlPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        pnlPanelOpcionesLayout.setVerticalGroup(
            pnlPanelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnModificarPlan.setText("4.- Modificar un plan");
        btnModificarPlan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver)
                    .addComponent(jlbTituloOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarRut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbExisteRut))
                    .addComponent(jlbTituloRutCliente)
                    .addComponent(txtRutBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnModificarPlan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(btnEliminarPlan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarPlanes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarPlan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(pnlPanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jlbTituloRutCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRutBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarRut)
                    .addComponent(jlbExisteRut))
                .addGap(37, 37, 37)
                .addComponent(jlbTituloOpciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarPlanes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(75, 75, 75))
            .addComponent(pnlPanelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPlan;
    private javax.swing.JButton btnBuscarRut;
    private javax.swing.JButton btnEliminarPlan;
    private javax.swing.JButton btnModificarPlan;
    private javax.swing.JButton btnMostrarPlanes;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jlbExisteRut;
    private javax.swing.JLabel jlbTituloOpciones;
    private javax.swing.JLabel jlbTituloRutCliente;
    private java.awt.Panel pnlPanelOpciones;
    private javax.swing.JTextField txtRutBuscado;
    // End of variables declaration//GEN-END:variables
}
